version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - lsio
        #ports:
      #- "53:53/tcp"
      #- "53:53/udp"
      #- "67:67/udp"
    environment:
      - TZ=America/New_York
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=griffin.chst.dev/pihole/
    volumes:
      - '/home/alphawrath/Documents/configs/pihole-data/etc-pihole/:/etc/pihole/'
      - '/home/alphawrath/Documents/configs/pihole-data/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
networks:
  lsio:
    external: true
