version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    networks:
      - lsio
    environment:
      #- PUID=1000
        #- PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/alphawrath/Documents/configs/swag-data:/config
    ports:
        #- 80:80
      - 8095:443
    restart: unless-stopped
networks:
  lsio:
    external: true
